### ISSUE TITLE
8.0悬浮窗权限适配

### ISSUE THREAD

**Issue by VainAnts** [rome753/ActivityTaskView#2]
直接 implementation 'cc.rome753:activitytaskview:3.8.0' ，然后使用ActivityTask.init(this, true);调用在8.0系统上报错如下
java.lang.RuntimeException: Unable to create application : android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@90a2195 -- permission denied for window type 2002
应该是8.0的悬浮窗权限未适配

还有一个问题：我的使用没有按照README里面的方式来，请问一下作者正确使用此库的方式是怎么样的

**Comment by rome753** [comment]
1. 安装ActivityTaskView这个app（不再是依赖库），启动并给予悬浮窗权限
2. 在你开发的App中加入如下类
https://github.com/rome753/ActivityTaskView/blob/master/app/src/main/java/cc/rome753/demo/ActivityTaskHelper.java
3. 在你开发的APP的Application类中加入代码
```
    @Override
    public void onCreate() {
        super.onCreate();

        if(BuildConfig.DEBUG) {
            ActivityTaskHelper.init(this);
        }
    }
```

**Comment by VainAnts** [comment]
感谢回复，为啥没采用依赖库了

**Comment by rome753** [comment]
依赖库耦合太重了，而且当多个APP都有悬浮窗时很乱。

**Comment by rome753** [comment]
8.0机型是啥？你看看能不能解决，解决的话可以提个Pull Request。

**Comment by VainAnts** [comment]
我使用依赖库在模拟器上报的上面的错误，真机可以运行，现在使用ActivityTaskView APP使用良好，感谢！
